### PR TITLE
Fix crash on Moto G (Android 5.1)

### PR DESCRIPTION
**Pull request by jm009**
OwnLog crashes as soon as I try to add the first log entry.

The fix follows this solution ("change the order of the attributes"):
https://stackoverflow.com/a/13047898/9404749

### CODE REVIEW

**Comment by jm009** [comment]
I just see there is another crash, when I am working with attachments. I will debug that too in the next days. If this patch was not merged until then, I will create an all-in-one pull request.

**Comment by jm009** [comment]
The crash(es) when working with attachments have gone...
There was no clear stack trace and error message. But with debugging through `android.view.LayoutInflator` I found an exception, that was not forwarded, indicating that there is a problem with attribute 'at position 2'.
With removing the android:layout_margin* and app:cardBackgroundColor it does not crash any more. Removing less of it => still crashes...

**Comment by SpiritCroc** [comment]
Thanks for contributing!

I was able to reproduce the crashes on an emulator running android 5.1.

While you correctly figured out which files/lines were causing issues, I don't agree with your fixes.
Your first fix does not change attribute order as you described, but removes the item element, moving its attribute to the parent ripple drawable. This indeed avoids the crash, but does not achieve the expected design, as it's not the way ripple drawables are supposed to be used (compare https://developer.android.com/reference/android/graphics/drawable/RippleDrawable)

Same goes for removing the attributes in the log_attachment layout files, fixing the crash by removing the problematic lines only also removes the desired effect they have.

From my testings, the real issue with lollipop are the styled attributes (those referenced using a '?' instead of an '@').
These are apparently not working as expected on lollipop and need a different approach. I'm not sure yet how I want to avoid the crash on lollipop and keep nice looking light and dark themes at the same time, but I will try to find some time for doing a proper fix if you don't have any objections.

Once I referenced colors directly instead of using styled attributes, the layout/margin attributes in the log_attachment layout files that you removed as well were not causing any issues either, and I have no idea way they would do so.

**Comment by jm009** [comment]
Thank you very much for carefully checking my changes.
I have to admit, that it is my first time that I did Android app programming. And to be honest I had no idea, that res/**.xml files are more than style sheets like in old html css... Much to learn... Thank you for explaining!
And thank you for OwnLog by the way!

**Comment by SpiritCroc** [comment]
No problem, everyone has to start somewhere.

Issue was something else actually than I first expected, hehe.
Can you confirm https://github.com/SpiritCroc/OwnLog/commit/dde744b468bd05bb02df2fd5e8721e701b80651f fixes it for you as well?

**Comment by jm009** [comment]
This fixes the crash for opening log entries with attachments. Yes, looks very nice with borders, and my changes had removed the borders, I can see that now :-)

But the app crashes, if the list of log entries is empty, and I press "+" (to add the first log entry). Can you reproduce that?

**Comment by jm009** [comment]
... works now... strange... No crash any more, when adding the first entry to the list...

**Comment by jm009** [comment]
Yep, I can not reproduce the crash.

**Comment by SpiritCroc** [comment]
Good

**Pull request closed without merging**
